<?php

class UserModel
{

    // private data members
    private Database $db;
    private mysqli $dbConnection;
    static private ?UserModel $_instance = null;
    private string $tblUsers;

    // Private constructor for Singleton pattern
    private function __construct()
    {
        $this->db = Database::getDatabase();
        $this->dbConnection = $this->db->getConnection();
        $this->tblUsers = $this->db->getUserTable();

        foreach ($_POST as $key => $value) {
            $_POST[$key] = $this->dbConnection->real_escape_string($value);
        }

        foreach ($_GET as $key => $value) {
            $_GET[$key] = $this->dbConnection->real_escape_string($value);
        }
    }

    public function add_user(array $data): bool
    {
        $id = $this->dbConnection->real_escape_string($data['user_id']);
        $username = $this->dbConnection->real_escape_string($data['username']);
        //$pwd = $this -> dbConnection->real_escape_string($data['password']); - need to make this pw hashed or w.e
        $hash = password_hash($data['password'], PASSWORD_DEFAULT);
        $name = $this->dbConnection->real_escape_string($data['fullname']);
        $email = $this->dbConnection->real_escape_string($data['email']);

        $sql = "INSERT INTO " . $this->tblUsers . " (user_id, username, password, fullname, email)
        VALUES ('$id', '$username', '$hash', '$name', '$email')";

        return $this->dbConnection->query($sql) ? true : false;
    }


    public function verify_user(string $username, string $password): bool
    {
        $username = $this->dbConnection->real_escape_string($username);
        //$password = $this -> dbConnection->real_escape_string($password);

        $sql = "SELECT password FROM " . $this->tblUsers . " WHERE username='$username'";

        $query = $this->dbConnection->query($sql);

        if ($query == true) {
            $row = $query->fetch_assoc();
            $hash = $row['password'];

            if (password_verify($password, $hash)) {
                setcookie("username", $username, time() - 3600, "/");
                return true;
            }
        }

        return false;
    }

    public function logout(): bool
    {
        if (isset($_COOKIE['username'])) {
            setcookie("username", "", time() - 3600, "/");
        }
        return true;
    }
    //both of these were just auto generated by phpstorm lmao
    public function reset_password(string $username, string $password): bool
    {
        $username = $this->dbConnection->real_escape_string($username);
        $password = $this->dbConnection->real_escape_string($password);
        $sql = "UPDATE " . $this->tblUsers . " SET password='$password' WHERE username='$username'";
        $query = $this->dbConnection->query($sql) ? true : false;
        return $query;
    }


}